INSERT INTO `news_channels` (`name`,`website`,`icon_url`,`meta`,`status`,`created_at`,`created_by`,`updated_at`,`updated_by`)
VALUES
    ('Detik','https://www.detik.com/','https://i.ibb.co/ZX1HDcY/detik.png',NULL,10,1562660614,1,1562660614,1),
    ('Kompas','https://www.kompas.com/','https://upload.wikimedia.org/wikipedia/commons/d/d7/Logo_Kompasdotcom.png',NULL,10,1562660614,1,1562660614,1),
    ('Tribun Jabar','https://jabar.tribunnews.com/','https://cdn-1.tstatic.net/img/icon/tribun-icon_32.png',NULL,10,1562660614,1,1562660614,1);

INSERT INTO `news` (`channel_id`,`title`,`slug`,`cover_path`,`source_url`,`source_date`,`content`,`featured`,`meta`,`seq`,`status`,`created_at`,`created_by`,`updated_at`,`updated_by`)
VALUES 
    (1,'Diviralkan Ridwan Kamil, Motor Listrik SDR Sudah Ada Sejak 2017','diviralkan-ridwan-kamil-motor-listrik-sdr-sudah-ada-sejak-2017','news/OAtwhwQs1r0F8cjpRv5FQUjfq0axj4EV.jpg','https://oto.detik.com/motor/d-4616781/diviralkan-ridwan-kamil-motor-listrik-sdr-sudah-ada-sejak-2017','2019-07-09','<p>Jakarta&nbsp;-&nbsp;Motor listrik SDR&nbsp;rakitan Bandung semakin terkenal semenjak ditunggangi Gubernur Jawa Barat, Ridwan Kamil. Tapi detikers tahu tidak ternyata motor listrik ini sudah ada di Indonesia sejak 2017 dan sudah melakukan berbagai pengujian.</p>
    <p>Seperti yang disampaikan pemilik PT Arindo Pratama, Soegeng Rijadi, kepada detikOto, Selasa (9/7/2019).</p>
    <p>Dulu 2017 saya masih datangkan secara CBU dari China, cuma sekarang yang ada di Indonesia itu sudah lebih bagus karena menggunakan part lokal, seperti shockbreakernya, ban, bahkan baterainya juga sudah lokal. Dan ini sudah dipatenkan sejak 2017," kata Soegeng.</p>
    <p>Motor listrik SDR&nbsp;ini jadi semangat baru buat perakitan lokal, dan dipastikan perjuangan untuk bisa ngaspal di jalanan bukan perkara mudah. Karena berbagai izin harus dilakukan untuk bisa benar-benar dikendarai dengan aman di jalanan.</p>
    <p>"Sejak 2017 kita sudah melakukan pengujian dan tidak lulus, dan akhirnya kita ganti menggunakan part lokal yang lebih baik dan 2018 baru kita dinyatakan lulus. Setelah itu baru kita urus surat menyuratnya dan di April 2019 baru selesai semuanya," katanya.</p>
    <p>Sebagai catatan motor listrik SDR sendiri diklaim memiliki daya maksimal 2.500 watt, dengan kemampuan menjelajah dengan jarak tempuh sejauh 70 km, dan input charger 220v/50Hz output charger 72v/3A, yang membutuhkan waktu sekitar 2 jam.</p>
    <p>Secara dimensi, motor layaknya roda dua fairing konvensional. Yakni PxLxT 2056x740x1054 mm, dengan ground clearance 156 mm. Rangka bajanya ditopang suspensi depan teleskopik dan shockbreaker belakang double swing shock absorber sehingga membuat motor nyaman dikendarai oleh semua kalangan.</p>
    <p>(lth/ddn)</p>',0,'{"read_count": 1}',NULL,10,1562666161,1,1562666192,1),
    (1,'23 Kecamatan di Cirebon Rawan Krisis Air Bersih Saat Kemarau','23-kecamatan-di-cirebon-rawan-krisis-air-bersih-saat-kemarau','news/88ez1hvss4F10uxc9LCUE2Ivi8T9Z5ia.jpg','https://news.detik.com/berita-jawa-barat/d-4616841/23-kecamatan-di-cirebon-rawan-krisis-air-bersih-saat-kemarau','2019-07-09','<p><strong>Cirebon</strong>&nbsp;- Puluhan kecamatan di Kabupaten Cirebon, Jawa Barat, berpotensi dilanda krisis air bersih akibat kekeringan. Badan Penanggulangan Bencana Daerah (BPBD) Kabupaten Cirebon menyalurkan bantuan air bersih ke sejumlah kecamatan yang sudah dilanda krisis.<br /><br />"Kalau melihat data yang ada, yang berpotensi krisis air bersih sebanyak 23 kecamatan dari 40 kecamatan yang ada di Kabupaten Cirebon. Krisis air bersih ini tersebar di 63 desa," kata Kasie Kedaruratan dan Logistik BPBD Kabupaten Cirebon Eman Sulaeman saat berbincang dengan detikcom di kantornya, Selasa (9/7/2019).</p>
    <p>Eman menyebut potensi krisis air bersih akibat kekeringan pada tahun ini cakupan wilayahnya lebih besar dibandingkan sebelumnya. Tahun lalu, kata dia, hanya 12 kecamatan yang dilanda krisis air bersih.&nbsp;<br /><br /></p>
    <center></center>
    <p>"Tahun lalu itu kita menyalurkan bantuan air bersih sebanyak 1,7 juta liter air, itu total selama kemarau. Tahun sekarang juga sudah ada beberapa desa yang mulai meminta bantuan karena krisis air bersih," ucap Eman.&nbsp;<br /><br />Lebih lanjut, Eman menyebut untuk saat ini beberapa desa yang sudah mengajukan di antaranya Kreyo, Klangenan, Slangit, Gebang Ilir, Greged, dan Waled. "Kita juga kerja sama dengan CSR perusahaan untuk penyaluran air bersih ke desa-desa," ucapnya.</p>
    <p>Selain penyaluran air bersih, menurut Eman, solusi lainnya untuk mengurangi dampak krisis adalah membuat sumur pantek. Namun, sumur pantek memiliki risiko yang tinggi terhadap lingkungan sekitar.<br /><br />"Sumur pantek itu harus digali dalam. Biasanya kerjasama dengan BMKG, tapi ada dampaknya," tutur Eman.<br /><br />Solusi utama untuk menanggulangi atau meminimalisir krisis air bersih, kata Eman, adalah dengan mengubah pola hidup masyarakat, seperti tidak boros air dan memanen air hujan.<br /><br />"Jangan boros air bersih. Halaman rumah itu harusnya jangan diplester, minimal ada ruang untuk penyerapan air. Terus, paling penting itu sistem memanen air hujan atau membuat penampungan," kata Eman.</p>
    <p>Eman tak menampik kesadaran masyarakat untuk menampung atau memanen air hujan masih minim. Saat ini pihaknya bekerja sama dengan Balai Besar Wilayah Sungai (BBWS) setempat untuk meningkatkan kesadaran masyarakat terkait sistem panen air hujan.&nbsp;<br /><br />"Kita akan sosialisasi dan membuat pelatihan kepada masyarakat, prosesnya bisa ditampung atau dialirkan ke sumur. Kita akan kerjasama dengan BBWS dan komunitas," ucapnya. <br /><strong>(tro/tro)</strong></p>',0,'{"read_count": 1}',NULL,10,1562666748,1,1562666910,1),
    (1,'Persija vs Persib, Polda Jabar Imbau Bobotoh Tak ke Datang GBK','persija-vs-persib-polda-jabar-imbau-bobotoh-tak-ke-datang-gbk','news/ePkS8Fwvl7h59fBNOx3TgYzZ1z96GvVR.jpg','https://news.detik.com/berita-jawa-barat/d-4617199/persija-vs-persib-polda-jabar-imbau-bobotoh-tak-ke-datang-gbk','2019-07-09','<p><strong>Bandung</strong>&nbsp;- Polda Jabar mengimbau Bobotoh untuk tidak datang langsung menonton pertandingan Persib Bandung vs Persija Jakarta di Stadion Stadion Gelora Bung Karno (GBK) yang akan digelar pada Rabu 10 Juli besok.<br /><br />"Imbauan untuk suporter Persib, Bobotoh, Viking, Bomber dan lainnya untuk tidak ke GBK," ucap Kabid Humas Polda Jabar Kombes Trunoyudo Wisnu Andiko saat dihubungi, Selasa (9/7/2019).</p>
    <p>Truno mengatakan imbauan tersebut diberikan merujuk pada surat yang dikeluarkan PT Liga Indonesia Baru (LIB) bernomor 216/LIB/VII/2019, tertanggal 5 Juli 2019. Pada surat itu, Bobotoh dinyatakan untuk tidak datang ke Jakarta.<br /><br /></p>
    <center></center>
    <p>"Ini supaya terselenggaranya pertandingan dengan lancar. Yang paling utama itu masalah keamanan dan ketertiban masyarakat," kata Truno.</p>
    <p>Sebagai gantinya, dia mendorong agar pemerintah di tiap-tiap daerah di Jabar menggelar acara nonton bareng. "Solusinya silakan menonton di daerah masing-masing. Kita mendorong Pemda bisa menggelar nobar," katanya.&nbsp;<br /><br />Pertandingan Persija vs Persib dalam lanjutan Liga 1 2019 dipentaskan di Stadion Utama Gelora Bung Karno. Pertandingan itu akan dilaksanakan pada Rabu (10/7/2019) besok. <br /><strong>(dir/tro)</strong></p>',0,'{"read_count": 3}',NULL,10,1562666887,1,1562666953,1),
    (2,'Pembebasan Lahan Tol Cisumdawu Terhambat, Ini Alasan Wagub Jabar','pembebasan-lahan-tol-cisumdawu-terhambat-ini-alasan-wagub-jabar','news/S6ILBKJOdtVt2AMmdeubNA45rrdcLFvZ.jpg','https://regional.kompas.com/read/2019/07/09/11261991/pembebasan-lahan-tol-cisumdawu-terhambat-ini-alasan-wagub-jabar','2019-07-09','<p>SUMEDANG, KOMPAS.com - Wakil Gubernur Jawa Barat Uu Ruzhanul Ulum menyinggung keberadaan rumah yang diduga menghambat pembebasan lahan untuk Tol Cisumdawu (Cileunyi, Sumedang, Dawuan) di wilayah Kabupaten Sumedang, Jawa Barat. Keberadaan tempat tinggal tersebut dijadikan alasan terhambatnya pembangunan Tol Cisumdawu yang sebelumnya ditargetkan akan rampung pada 2019 ini. "Informasi yang kami terima ada rumah (baru) yang dibangun, tapi kenyataannya kosong. Sehingga, menghambat pembebasan lahan," ujar Uu kepada sejumlah wartawan usai membuka TMMD (TNI Manunggal Membangun Desa) ke 105 di Desa Padanaan, Kecamatan Paseh, Sumedang, Selasa (9/7/2019). Menurut Uu, pihak provinsi hanya bisa mendorong Pemkab Sumedang untuk membantu mempercepat proses pembebasan lahan di wilayah Sumedang. Mengenai kemungkinan adanya calo tanah yang bermain di kawasan yang akan dilalui proyek tol, Uu tidak berkomentar banyak. "Informasinya seperti itu, tapi saya tidak tahu (soal calo tanah), karena kami tidak terlibat di dalamnya. Yang pasti, Pemprov mendorong agar dalam waktu satu tahun ke depan, tol sudah bisa dioperasikan. Kami meminta Pemkab Sumedang berperan aktif kaitannya dengan percepatan pembebasan lahannya," kata Uu. Baca juga: Polisi: Hanya Mobil Ukuran Kecil yang Bisa Lewat Tol Cisumdawu Uu mengatakan, akses Tol Cisumdawu cukup vital keberadaannya, karena akan menghubungkan Bandung menuju Bandara Kertajati, Jawa Barat. Untuk itu, diharapkan target Tol Cisumdawu 1 tahun rampung sesuai dengan arahan Kementerian Pekerjaan Umum dapat terealisasi. "Bila Tol Cisumdawu ini rampung, akses menuju Bandara Kertajati akan lebih mudah dijangkau," kata Uu.</p>',0,'{"read_count": 1}',NULL,10,1562667278,1,1562667288,1),
    (2,'PIKF Kembali Digelar, Ribuan Layangan Akan Terbang di Langit Pangandaran','pikf-kembali-digelar-ribuan-layangan-akan-terbang-di-langit-pangandaran','news/gsQK33is6Aitu4t4mBz7j2ULDOx92u4P.jpg','https://travel.kompas.com/read/2019/07/08/125137127/pikf-kembali-digelar-ribuan-layangan-akan-terbang-di-langit-pangandaran','2019-07-09','<p>KOMPAS.com - Bupati Pangandaran Jeje Wiradinat memastikan event Pangandaran International Kite Festival (PIKF) akan kembali digelar tahun ini, tepatnya pada 12 hingga 14 Juli. Berlokasi di lapangan Katapang Doyong Pantai Timur, Pangandaran, Jawa Barat, event itu adalah festival tahunan yang menerbangkan ribuan layang-layang di langit Pangandaran selama seharian penuh. Namun khusus tahun ini, semua peserta festival dipastikan akan menyiapkan desain unik dan menarik, seperti adanya layang-layang balon, dua dimensi, tiga dimensi, sport, dan tidak ketinggalan layang-layang bertemakan kearifan lokal. "Pesertanya makin variatif dan makin banyak. Yuk ramai-ramai ke PIKF lalu saksikan layang-layangnya," ujar Jeje sesuai keterangan tertulis yang Kompas.com terima, Senin (8/7/2019).</p>
    <p>Baca juga: Layang-Layang Tidak Hanya Satu, Ini Jenis-Jenisnya</p>
    <p>Selain festival layang-layang, lanjut Jeje, PIKF juga turut dimeriahkan dengan agenda festival seni budaya baik lokal maupun internasional. "Itu karena 10 negara sahabat seperti Jepang, Italia, Amerika Serikat, Selandia Baru, Thailand, dan Malaysia juga ikut berpartisipasi," ucap dia. Lalu akan ada juga pameran dari pelaku UMKM, wisata kuliner khas Pangandaran, bersih-bersih pantai, lomba mewarnai layang-layang, dan fashion show. "Keseruannya akan terus berlanjut sampai malam hari," jelas Jeje. Baca juga: Kabar Gembira, PT KAI Luncurkan Rute Baru ke Pangandaran Sementara itu, Menteri Pariwisata (Menpar) Arief Yahya juga menyambut positif ajang PIKF yang terus konsisten digelar. Hal itu karena dapat menyedot ribuan turis lokal dan asing datang ke Pangandaran. "Momennya pas karena bertepatan dengan libur sekolah, PIKF saya prediksi akan sangat ramai dan memberikan kesan yang tak terlupakan bagi wisatawan," ujar Arief.</p>',0,'{"read_count": 0}',NULL,0,1562667410,1,1562667410,1),
    (2,'Macan Kumbang Slamet, Takut Saat Lihat Manusia hingga Dipasangi GPS','macan-kumbang-slamet-takut-saat-lihat-manusia-hingga-dipasangi-gps','news/SyXgEKAVhCaoknSRo2uhWNwwhSO3GckL.jpg','https://regional.kompas.com/read/2019/07/09/11112831/macan-kumbang-slamet-takut-saat-lihat-manusia-hingga-dipasangi-gps','2019-07-09','<p>SUKABUMI, KOMPAS.com - Seekor macan tutul/ macan kumbang jawa (Panthera pardus melas) yang diberi nama Slamet Ramadhan akan dilepas di kawasan Balai Taman Nasional Gunung Ciremai (TNGC), Kuningan, Jawa Barat, Selasa (9/7/2019). Satwa liar dilindungi ini sempat masuk pemukiman Kampung Cimalingping, Desa Sindangsari, Kecamatan Kasomalang, Subang, Sabtu (1/6/2019). Slamet bahkan melukai seorang warga, Juju Juangsih (62). Sebelum dilepas, karnivora besar ini mendapatkan rehabilitasi di Pusat Penyelamatan Satwa Cikananga (PPSC) Nyalindung, Sukabumi sejak 28 Juni hingga 8 Juli 2019. "Kondisi macan tutul sudah siap di-release, rencanaya besok (Selasa)," ujar Kepala Bidang Wilayah ll Soreang - Balai Besar Konservasi Sumber Daya Alam (BBKSDA) Jawa Barat, Pupung Purnawan kepada Kompas.com di PPSC Nyalindung, Sukabumi, Senin (8/7/2019) petang.</p>
    <p>Baca juga: Kisah Slamet Ramadhan, Macan Kumbang yang Bikin Geger karena Masuk Rumah Warga</p>
    <p>Pupung menuturkan, kondisi satwa siap dilepas berdasarkan data dari para dokter hewan yang menanganinya di PPSC. Tim dokter hewan telah menanganinya baik secara fisik maupun psikologi satwa. "Di sini (PPSC), macan tutul ini sudah mendapatkan penanganan selama seminggu. Dan petang ini dengan perjalanan malam akan dievakuasi ke Kuningan," ujar mantan Kepala Bagian Tata Usaha BBKSDA Papua.</p>
    <p>Kondisi sehat</p>
    <p>Dokter hewan dari Direktorat Jenderal Konservasi Sumber Daya Alam dan Ekosistem (Ditjen KSDAE) Dedi Candra mengatakan, secara umum, macan tutul jantan ini dalam kondisi baik. Pihaknya telah melaksanakan pemeriksaan fisik dan laboratorium yang hasilnya dalam ketegori baik. Dari pemeriksaan perilakunya, macan tutul berusia remaja ini masih bisa makan dan sifat liarnya pun masih sangat terlihat. "Hal ini ditandai dengan menghindari kontak dengan manusia. Bila ada orang langsung sembunyi. Di sini (PPSC) ada fasilitas yang memang satwanya bisa bersembunyi, ada semak-semaknya," kata Dedi. Menurut dia, pihaknya sudah melakukan pemeriksaan dugaan penyakit yang biasa menular dari hewan-hewan jenis anjing dan kucing. "Hasilnya juga negatif, tidak ditemukan penyakit," ujar Dedi. Baca juga: Dirawat 27 Hari, Macan Kumbang yang Masuk Rumah Warga Akan Dilepaskan Dipasangi GPS collar Rudiar Anisa, dokter hewan dari Copenhagen Zoo - Baluran Program mengatakan, macan tutul yang akan dilepasliarkan di kawasan Gunung Ciremai tersebut sudah dipasangi Global Positioning System (GPS) Collar. Alat GPS Collar ini telah dipasang di bagian leher, pada bagian lingkaran terkecil macan tutul. Alat tersebut akan mengirimkan titik koordinat dan dapat langsung dipantau di atas peta digital. Tujuan pemasangannya, menurut Rudiar, untuk mendapatkan data pergerakan dan mengetahui posisi macan tutul. Alat tersebut sudah di atur untuk melaporkan setiap 30 menit sekali. "Sehingga, nantinya setelah sekian lama akan mengetahui dan bisa dipetakan pergerakannya," ujar Rudiar. Pantauan Kompas.com, macan tutul yang akan dilepasliarkan di TNGC ini dimasukan ke dalam kandang angkut dengan mobil khusus Wildlife Rescue Unit Ditjen KSDAE. Kandang angkutnya terbuat besi dengan ukuran panjang 190 sentimeter, lebar 82 sentimeter dan tinggi 150 sentimeter.</p>',0,'{"read_count": 0}',NULL,0,1562667569,1,1562667569,1),
    (2,'Tiga Calon Jemaah Asal Jawa Barat Batal Berangkat Haji karena Hamil Muda dan Alasan Kesehatan','tiga-calon-jemaah-asal-jawa-barat-batal-berangkat-haji-karena-hamil-muda-dan-alasan-kesehatan','news/NA2AB8k2ZuuEUnbU9Gczm9goAiQIIRr3.jpg','https://megapolitan.kompas.com/read/2019/07/09/15125111/tiga-calon-jemaah-asal-jawa-barat-batal-berangkat-haji-karena-hamil-muda','2019-07-09','<p>BEKASI, KOMPAS.com - Panitia penyelenggara ibadah haji (PPIH) Jakarta-Bekasi mencatat, sudah ada tiga calon jemaah haji asal Jawa Barat yang batal terbang ke Tanah Suci, sejak Minggu (7/7/2019) hingga Selasa (9/7/2019), karena alasan kesehatan. "Satu hamil, satu sakit, satu ekses (mengikuti pendamping). Total ada tiga calon haji yang batal berangkat," ujar Yani Dwiyuli Setiani, Kepala Bidang Haji PPIH Jakarta-Bekasi saat ditemui di Asrama Haji Embarkasi Bekasi, Selasa siang. Calon haji pertama yang batal berangkat tercatat atas nama Neng Sarah Asep (25), calon haji kloter 2 asal Cianjur. Sarah batal berangkat ke Mekkah tahun ini lantaran usia kandungannya baru berusia 11 pekan, sedangkan usia kehamilan yang diizinkan untuk mengikuti ibadah haji adalah 14-26 pekan. Dua calon haji yang gagal berangkat selanjutnya atas nama Suwarno dan Sri Wahyuni, calon haji kloter 6 asal Kabupaten Bandung. Suwarno diketahui mengidap gagal ginjal stadium 4, sedangkan Sri Wahyuni, istrinya, pilih mendampingi suaminya di rumah sakit.</p>
    <p>Baca juga: Koper Jemaah Haji Dibongkar, Isinya Rokok dan Obat dalam Jumlah Berlebihan</p>
    <p>"Di Peraturan Menteri Kesehatan Nomor 15 Tahun 2016 diatur soal istithaah kesehatan jemaah haji atau kesehatan yang tidak memenuhi syarat, kriterianya itu salah satunya gagal ginjal stadium 4 atau 5 yang sudah perlu cuci darah seminggu 1-2 kali," jelas Yani. Sebanyak 4.040 calon haji yang terbagi dalam 10 kloter asal Jawa Barat telah berangkat dari Asrama Haji Embarkasi Bekasi sejak Minggu (7/7/2019) hingga Selasa (9/7/2019) pukul 13.50 WIB, untuk keberangkatan haji 1440 Hijriah. Selain itu, masih tersisa dua kloter asal Depok dan Kabupaten Bekasi yang akan diberangkatkan pada sore nanti menuju Bandara Soekarno-Hatta. Total, terdapat 97 kloter calon haji asal Jawa Barat yang akan berangkat ke Arab Saudi dengan lebih dulu menginap di Asrama Haji Embarkasi Bekasi sehari sebelum terbang. Pemberangkatan jamaah haji masih terus berlangsung hingga 5 Agustus 2019 nanti.</p>',0,'{"read_count": 0}',NULL,0,1562667678,1,1562667678,1),
    (3,'Dispagtan Kota Bandung Raih Stand Terbaik Tingkat Nasional','dispagtan-kota-bandung-raih-stand-terbaik-tingkat-nasional','news/2q4sL3jYjYDSFkqiRw1PdfMYm3pREOJ2.jpg','https://jabar.tribunnews.com/2019/07/09/dispagtan-kota-bandung-raih-stand-terbaik-tingkat-nasional','2019-07-09','<p>TRIBUNJABAR.ID, BANDUNG - Dinas Pangan dan Pertanian (Dispangtan ) Kota Bandung meraih Juara Pertama Stand Terbaik Nasional Tingkat Kabupaten/Kota.</p>
    <p>Prestasi diraih Dispangtan Kota Bandung saat mengikuti 19th Indonesia AgroFood Expo 2019 selama empat hari 27-30 Juni 2019 di Hall B Jakarta Convention Center.</p>
    <p>Plt Kepala Dispangtan Kota Bandung Ir Elly Wasliah mengatakan, penghargaan tersebut merupakan bentuk prestasi yang membanggakan karena bisa mewakili Kota Bandung meraih Juara Pertama di event Pameran Tingkat Nasional pada Tahun 2019</p>
    <p>"Pameran digelar sebagai sarana promosi produk dan potensi investasi agribisnis / agroindustri untuk pasar domestik dan internasional," ujar Elly.</p>
    <p>Pameran Indonesia Agrofood Expo diselenggarakan setiap tahun sejak tahun 2001 atas dukungan Kementerian Pertanian RI.</p>
    <p>Pameran diselenggarakan bersamaan dengan Indonesia International Modern Agriculture Expo 2019 dan Indonesia Coffee, Cacao &amp; Tea Festival 2019. Pameran diikuti sekitar 155 peserta terdiri dari Kementerian, Dinas Provinsi, Dinas Kabupaten/Kota dan Swasta.</p>
    <p>Selama pameran selain display produk unggulan, teknologi, alat dan mesin serta jasa pendukung lainnya, juga diadakan kegiatan pendukung antara lain talkshow dan presentasi peluang investasi sektor pertanian, business matching (buyers meet sellers), launching product, festival kopi, kakao &amp; teh, dan lainnya.</p>
    <p>Pemerintah&nbsp;<a title="Kota&nbsp;Bandung" href="https://jabar.tribunnews.com/tag/kota-bandung">Kota&nbsp;Bandung</a>&nbsp;melalui&nbsp;<a title="Dinas&nbsp;Pangan&nbsp;dan&nbsp;Pertanian&nbsp;Kota&nbsp;Bandung" href="https://jabar.tribunnews.com/tag/dinas-pangan-dan-pertanian-kota-bandung">Dinas&nbsp;Pangan&nbsp;dan&nbsp;Pertanian&nbsp;Kota&nbsp;Bandung</a>&nbsp;turut serta berpartisipasi dalam even tahunan ini. Banyak ditampilkan produk olahan makanan hasil pertanian di stand yang memiliki luas 6 x 3 meter ini.</p>
    <p>Selain itu pula turut dipromosikan produk Teh Arafa Cigadung serta Kopi Bandung Manglayang yang menjadi primadona selama pameran berlangsung.</p>
    <p>Penghargaan Juara Pertama diserahkan langsung oleh Dirjen Perkebunan Kementerian Pertanian Republik Indonesia dan Direktur Utama PT. Wahyu Promo Citra selaku promotor kegiatan dan diterima oleh Sekteraris Dispangtan&nbsp;<a title="Kota&nbsp;Bandung" href="https://jabar.tribunnews.com/tag/kota-bandung">Kota&nbsp;Bandung</a>&nbsp;Ir Tamsil Tahir MS</p>
    <p>Kopi Bandung Manglayang turut serta meraih penghargaan sebagai kopi dengan citarasa terbaik kategori SILVER pada uji Coffee Lovers Preperency Taste yang diselenggarakan di JCC Senayan pada tanggal 29 Juni 2019.</p>
    <p>Elly mengatakan penghargaan ini tentunya menjadi motivasi bagi kita semua untuk dapat berkarya lebih baik lagi di masa mendatang, karena mempertahankan akan jauh lebih sulit daripada meraihnya.(tiah sm)</p>',0,'{"read_count": 0}',NULL,0,1562668042,1,1562668042,1),
    (3,'Tembus 48.231 Pendaftar, UPI Peringkat 4 Peminat SBMPTN 2019 Terbanyak se-Indonesia','tembus-48231-pendaftar-upi-peringkat-4-peminat-sbmptn-2019-terbanyak-se-indonesia','news/N97SCQIVRgVJi5WifbB3eJI4oA84Gowc.jpg','https://jabar.tribunnews.com/2019/07/09/tembus-48231-pendaftar-upi-peringkat-4-peminat-sbmptn-2019-terbanyak-se-indonesia','2019-07-09','<p>Laporan Wartawan Tribun Jabar, Hilda Rubiah</p>
    <p>TRIBUNJABAR.ID, BANDUNG- Pada penetapan hasil SBMPTN oleh Lembaga Tes Masuk Perguruan Tinggi (LTMPT), Selasa (9/7/2019), Universitas Pendidikan Indonesia ( UPI ) masuk empat besar perguruan tinggi negeri yang paling diminati.</p>
    <p>Dari hasil pengumuman SBMPTN 2019, Universitas Pendidikan Indonesia ( UPI ) menempati posisi empat di urutan PTN yang paling diminati di Indonesia.</p>
    <p><br />Total, ada 48.231 calon mahasiswa yang mendaftar masuk UPI.</p>
    <p>Dari 48.231 total jumlah pendaftar tersebut, UPI di urutan pertama PTN dengan peminat terbanyak untuk prodi Sosial dan Hukum (Soshum). Total, ada 34.544 pendaftar untuk prodi Soshum UPI.</p>
    <p>Kepala Humas UPI, Dr. Yuliawan Kasmahidayat, mengatakan pihaknya bersyukur mengetahui data itu.</p>
    <p>Menurutnya, banyaknya pendaftar tersebut sebagai cerminan masyarakat makin mempercayai UPI untuk memberikan layanan pendidikan tinggi.</p>
    <p>"Alhamdulillah, berarti memang tahun ini masyarakat telah banyak mengetahui keberadaan UPI dengan berbagai prodi kependidikan dan non kependidikan," ujar Kepala Humas UPI, Dr. Yuliawan Kasmahidayat, kepada Tribun Jabar, melalui sambungan telepon, Selasa (9/7/2019).</p>
    <p>Dr. Yuliawan Kasmahidayat, mengatakan dari 48.231 total jumlah pendaftar tersebut UPI menerima kuota sekira 3.793 calon mahasiwa baru melalui jalur SBMPTN 2019.</p>
    <p>Jumlah itu itu setara 45 persen dari total calon mahasiswa baru untuk program sarjana, sebanyak 9.370 orang.</p>
    <p><br />UPI membuka 81 program studi pilihan, dengan daya tampung 846 kursi untuk kelompok peserta Sains dan Teknologi (Saintek), dan 2.947 kursi untuk kelompok Sosial Humaniora (Soshum).</p>
    <p>Menurut Dr. Yuliawan Kasmahidayat, peserta yang lulus di UPI tidak hanya dipersiapkan untuk mengajar, tetapi juga dipersiapkan dapat bersaing dengan lulusan PT dengan basis non kependidikan.</p>
    <p>Selanjutnya Dr. Yuliawan Kasmahidayat, mengimbau pendaftar yang dinyatakan lulus SBMPTN 2019 di UPI agar melakukan resgitrasi atau daftar ulang.</p>
    <p>"Resgitrasi ini harus dilakukan sebagai verifikasi peserta lulus tercatat sebagai mahasiswa baru UPI ajaran tahun 2019," ujarnya.</p>
    <p>Calon mahasiswa baru UPI yang diterima melalui SBMPTN tahun akademik 2019/2020 juga dapat dilihat melalui laman http://sbmptn.ac.id atau http://pmb.upi.edu.</p>
    <p>Bagi calon mahasiswa baru yang lulus SBMPTN dan Bidikmisi wajib mengisi biodata lulus SBPMTN 2019 secara daring pada laman pmb.upi.edu, tanggal 10 sanpai dengan 15 Juli 2019.</p>
    <p>Berikutnya semua calon mahasiswa baru yang lulus SBMPTN wajib melakukan verifikasi data di Direktorat Akademik UPI pada tanggal 31 Juli sampai dengan 5 Agustus 2019.</p>
    <p><br />Setelah terdaftar, sebelum memulai perkuliah perdana pada 1 September mendatang, mahasiswa baru akan mengikuti masa pendampingan pengenalan kampus yang dikelola oleh BEM.</p>',0,'{"read_count": 0}',NULL,0,1562668237,1,1562668237,1),
    (3,'Rudjak Ciherang, Jajajan yang Sudah Berusia 94 Tahun, Rasanya Manis, Asem, Pedas, dan Segar','rudjak-ciherang-jajajan-yang-sudah-berusia-94-tahun-rasanya-manis-asem-pedas-dan-segar','news/B4QD9LLUaUli24w3trpRa6wuPqQJWODK.jpg','https://jabar.tribunnews.com/2019/07/09/rudjak-ciherang-jajajan-yang-sudah-berusia-94-tahun-rasanya-manis-asem-pedas-dan-segar','2019-07-09','<p>Laporan Wartawan Tribun Jabar, Mumu Mujahidin</p>
    <p>TRIBUNJABAR.ID, BANDUNG - Siang-siang gini enaknya makan yang seger-seger ya gais. Rujak kayaknya bisa menjadi satu pilihan santap siang Anda hari ini.</p>
    <p>Karena rujak sangat enak dinikmati di siang hari. Rasa asem, manis, pedas dan segar dipercaya bisa mengembalikan mood Anda yang tengah sibuk bekerja.</p>
    <p><br />Nah di Banjaran, Kabupaten Bandung, ada satu tempat ''ngarujak'' atau tempat makan rujak yang legendaris. Sampai saat ini rujak ini masih menjadi favoritnya ibu-ibu.</p>
    <p>Adalah Rudjak Ciherang di Jalan Soreang-Banjaran No 81, RT 03/10 Kampung Ciherang, Desa Kiangroke, Kecamatan Banjaran, Kabupaten Bandung.</p>
    <p>Asep Rosadi (55) pemilik sekaligus salah satu generasi penerus keempat Rudjak Ciherang, menuturkan Rudjak Ciherang ini sudah ada jauh sebelum negara Indonesia merdeka, yakni pada tahun 1925 atau sudah 94 tahun.</p>
    <p>Dulu rujak ini dijual dengan cara dijajakan atau digendong menggunakan bakul oleh nenek buyutnya. Kini rujak ini dijual di sebuah toko kecil yang sangat sederhana oleh generasi ke empat keluarga ini.</p>
    <p>Keistimewaan Rudjak Ciherang terletak pada bumbu rujaknya yang masih dipertahankan sejak dulu hingga sekarang. Bumbu Rudjak Ciherang ini memiliki rasa dan aroma yang khas, karena telah ditambahkan buah honje atau buah kecombrang di dalamnya.</p>
    <p>Bumbu Rudjak Ciherang ini memiliki komposisi bumbu rujak pada umumnya, yakni gula aren, asem jawa, garam, dan cabai. Terakhir bumbu rujak ini diberi irisan kecombrang sehingga rasa dan aromanya berbeda dengan bumbu rujak lainnya.</p>
    <p>Rasa asem manis dari gula aren dan asem jawa memang terasa dominan saat mencoba bumbu rujak ini. Ditambah aroma dari kecombrang yang sangat khas sehingga ada after taste yang sangat segar setelah menikmati Rudjak Ciherang ini.</p>
    <p>Rujak memang sangat identik dengan rasa pedas dan segar. Pemilik Rudjak Ciherang sengaja tidak menambahkan cabai pada bumbu rujak ini. Namun mereka menyediakan bubuk cabai merah kering, untuk mengatur tingkat kepedasan pelanggannya, sesuai selera.</p>
    <p>Pemilik Rudjak Ciherang ini selalu mengombinasikan irisan buah dan umbi-umbian segar seperti jambu air, ubi, bengkoang, dan mentimun. Serta buah musiman seperti, kedongdong, mangga dan jambu.</p>
    <p>"Rujak ini dijual Rp 10 ribu per porsi, bisa dimakan langsung di sini, bisa juga dibungkus pake daun pisang. Kami juga menjual bumbu rujaknya saja Rp 25 ribu per cup," tutur Asep.</p>
    <p>Salah satu penggemar Rudjak Ciherang asal Pangalengan Ica (51) menuturkan ia bersama keluarganya sangat sering ''ngarujak'' di Rudjak Ciherang. Bahkan Ica juga kerap sengaja berbelanja banyak untuk kebutuhan oleh-oleh ke luar kota.</p>
    <p>"Ini aja untuk dibawa ke Mekah, buat ibadah nanti. Di sana kan panas jadi cocok untuk dibawa ke sana (Mekah). Jadi nanti tinggal beli mangga dan jambu saja di sana," ujarnya di lokasi.</p>
    <p>Menurutnya bumbu Rudjak Ciherang sangat beda dengan bumbu-bumbu rujak pada umumnya. Penambahan bahan buah kecombrang membuat Rudjak Ciherang menjadi lebih segar beraroma khas.</p>
    <p>"Jadi rasanya beda banget sama rujak-rujak lainnya. Bumbunya asem-asem pedas gimana gitu, ditambah segar dari kecombrangnya. Jadi pas dimakan itu ada aroma kecombrangnya gitu," katanya.</p>
    <p>Penggemar rujak lainnya Ineu Armina (54) asal Tamansari Kota Bandung juga mengaku suka sekali dengan Rudjak Ciherang ini. Ia kerap membeli bumbu rujaknya saja khusus untuk acara reunian atau arisan bersama ibu-ibu koleganya.</p>
    <p>"Iya biasanya kalau mau ada arisan atau reunian pasti beli rujak ke sini. Soalnya enak teman-teman pada ketagihan, suka pada nanyain beli dimana bumbu rujaknya," katanya.</p>',0,'{"read_count": 0}',NULL,0,1562668403,1,1562668403,1),    
    (3,'Duel Lawan Persija Tak Mudah Bagi Persib, Masa Lalu Robert Alberts Lawan Persija Tidak Memuaskan','duel-lawan-persija-tak-mudah-bagi-persib-masa-lalu-robert-alberts-lawan-persija-tidak-memuaskan','news/GSyyxSujEpA7Yswd9eClHKlv7HWDo076.jpg','https://jabar.tribunnews.com/2019/07/09/duel-lawan-persija-tak-mudah-bagi-persib-masa-lalu-robert-alberts-lawan-persija-tidak-memuaskan','2019-07-09','<p>TRIBUNJABAR.ID, BANDUNG - PelatihPersib Bandung, Robert Alberts, menghadapi tantangan berat saat bertemu dengan Persija Jakarta di Stadion Utama Gelora Bung Karno, Rabu (10/7).</p>
    <p>Selain performa Persib Bandung yang sedang terpuruk, rekor pertemuan Robert Alberts menghadapi Persija pun tak mulus.<br />Dari lima pertemuan terakhir menghadapi Persija Jakarta, Robert Alberts hanya mampu mengemas satu kemenangan. Kemenangan ini diraih Robert Alberts saat masih menukangi PSM Makassar tahun 2017 di kompetisi Liga 1.</p>',0,'{"read_count": 0}',NULL,0,1562668816,1,1562668816,1);