version: '3'
services:
  api:
    build:
      context: ./api
      args:
        - APP_VERSION=${VERSION}
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-api:${VERSION}
    networks:
      - internal
    depends_on:
      - database
      - redis
    env_file:
      - .env-dev
    volumes:
      - ./api:/srv
      - /srv/vendor
      - vol_storage:/srv/web/storage
    ports:
      - 81:80

  queue:
    build:
      context: ./api
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-api:${VERSION}
    networks:
      - internal
    depends_on:
      - database
      - api
      - redis
    env_file:
      - .env-dev
    volumes:
      - ./api:/srv
      - /srv/vendor
      - vol_storage:/srv/web/storage
    restart: on-failure
    command: ['bash','-c','/srv/yii queue/listen --verbose']

  database:
    build:
      context: ./database
    image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-app/sapawarga-backend-database:${VERSION}
    networks:
      - internal
    ports:
      - 3306:3306
    env_file:
      - .env-dev
    volumes:
      - vol_mysql_data:/var/lib/mysql

  app_bansos_excel:
    image:  registry.gitlab.com/jdsteam/sapa-warga/sapawarga-process-bansos-excel:no-cmd
    depends_on:
      - api
    env_file:
      - .env-dev
    networks:
      - internal
    ports:
      - 8003:8000
    restart: on-failure
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis:6.0.5-alpine 
    restart: on-failure
    networks:
      - internal 
    ports:
      - 6379:6379
    
  memcached:
    image: memcached:latest
    restart: on-failure
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  vol_storage:
    driver: local
  vol_mysql_data:
    driver: local
